// Copyright 2026 ZeroCloud SDK contributors. SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import path from 'node:path';
import { digest, readJson, root } from './candidate.mjs';
const assets = path.join(root, 'src/main/resources/net/zerocloud/magika/model');
const manifest = readJson(path.join(assets, 'asset-manifest.json'));
for (const asset of manifest.assets) assert.equal(digest(fs.readFileSync(path.join(assets, asset.file))), asset.sha256);
const config = readJson(path.join(assets, 'config.min.json'));
const kb = readJson(path.join(assets, 'content_types_kb.min.json'));
const labels = [...new Set([...config.target_labels_space.map(label => config.overwrite_map[label] || label), 'empty', 'txt', 'unknown'])].sort();
const document = `# Supported final type labels\n\n`
  + `Generated by \`node scripts/release/supported-types.mjs\` from the authenticated\n`
  + `\`standard_v3_3\` asset set at upstream \`${manifest.upstreamCommit}\`.\n`
  + `Config SHA-256: \`${manifest.assets.find(asset => asset.file === 'config.min.json').sha256}\`.\n\n`
  + `The model has ${config.target_labels_space.length} raw labels. Apply its \`overwrite_map\`, then add\n`
  + `the short-content/empty rules and confidence fallbacks (\`empty\`, \`txt\`, \`unknown\`):\n`
  + `this yields the ${labels.length} possible final labels below. \`randombytes\` and\n`
  + `\`randomtxt\` are raw-only labels, rewritten to \`unknown\` and \`txt\` in every mode.\n`
  + `The knowledge base contains ${Object.keys(kb).length} entries; entries outside this derived\n`
  + `set are not a support claim. This list describes the result vocabulary, not\n`
  + `accuracy for every category. Reference tests do not cover every model class.\n`
  + `MIME strings preserve the fixed metadata; null MIME uses its text/binary fallback.\n\n`
  + `| Final label | MIME | Origin |\n| --- | --- | --- |\n`
  + labels.map(label => `| \`${label}\` | \`${kb[label].mime_type ?? (kb[label].is_text ? 'text/plain' : 'application/octet-stream')}\` | ${label === 'empty' ? 'Empty rule' : label === 'unknown' ? 'Mapping / rule / confidence fallback' : label === 'txt' ? 'Model / mapping / rule / confidence fallback' : 'Mapped model vocabulary'} |`).join('\n') + '\n';
const output = path.join(root, 'docs/supported-types.md');
if (process.argv.includes('--check')) assert.equal(fs.readFileSync(output, 'utf8'), document, 'Supported types document is stale');
else fs.writeFileSync(output, document);
console.log(`Supported final labels: ${labels.length}; raw model labels: ${config.target_labels_space.length}; knowledge-base entries: ${Object.keys(kb).length}`);
